### ISSUE TITLE
Enumerate example fails to compile

### ISSUE THREAD

**Issue by maxdobeck** [tomaka/cpal#311]
https://github.com/tomaka/cpal/blob/master/examples/enumerate.rs fails to compile 

```
error[E0599]: no method named `name` found for type `cpal::HostId` in the current scope
  --> examples/enumerate.rs:12:32
   |
12 |         println!("{}", host_id.name());
   |                                ^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `audio-test`.

```

I'm on Ubuntu 18.04.2 LTS 
rustc 1.35.0 (3c235d560 2019-05-20)
cargo 1.35.0 (6f3e9c367 2019-04-04)

Happy to send pull request or document changes, from what I read it looks like things are changing and this example isn't expected to work on cpal 0.10.0.

**Comment by ishitatsuyuki** [comment]
This isn’t supposed to work on the release version, because APIs are changed in master. Please checkout the release tag, or compile the example with master source.

**Comment by maxdobeck** [comment]
Changing cargo.toml to the below worked, thank you
```
[dependencies]
cpal = { git = "https://github.com/tomaka/cpal", barnch = "master" }
```

Will the next versions reflect the api changes?  Great project, look forward to using it.
